sudo: false
language: python
python: 3.5
script: true
deploy:
  provider: pypi
  user: qubvel
  password:
    secure: pupCRmDA2kiUoNy2M/c88ev9xbt+Twpeu2N/S85oTkqZuSh8enMIPxouPaFC/xlBYyEkUur9PJ7Zd3DKQcP8cCd4DHNEZT+9yA1/OemnWcZcHydAKqbNen6AFxFs05pGzhfmlMTmHD1yeKaf5O8qpCsLTo5A/yavTOBknA3TnBXWn9DCz326C1N7CuA/zXwOQvTPwQ4cj73QsIxNqVt55JTgU91NGZpfHvLUXvfvyTYDyjCHqYAlx1YWdCchsP7lKoOo7nvtaV+JWsD0JGV5UT5J4qZzyIZzZQhoA1liat1hE8YsHm/DxNxNQk/xIa4ur0cPp+Y1cN2Rd6YNl06meROpjA3/7xIkRdSwNwLNwN7u97g75vIE6ViXurB2rQ11OBdi2M9BBDdRtoNCOMANMU4KNPt9hzdTGPYxz9vn6E3fx9iyJrBR1puvEwaSGn5qhRi8FH40gATeCfZ0Ixmzdd4ZofL2oCCcr6+oEL7PLyNGYriV+/ITpFgQSMepR8CKc0Ce3bbceIV142iOMbUKyD0fYkocXy3Vb//A5BNDWP/tyFEOlRoTxQdHB4t2aE6Ay4VqGDmMnS2VW7AZbQxgfTO9gqhfs1n2yt+kHl5kdhcZxQoC16PRiUZa/e5REDyjOfc0b5YJf7ietyZAwdgleR8itFPtS813BB1t7dYHTts=
  on:
    tags: true
  skip_existing: true
